### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by ivklgn** [sweetjes/roflanbuldiga#1]
коммиты типа `Add files via upload` - не описывают суть фиксации. Текст комментария в коммитах должен отражать краткое описание изменений

**Comment by ivklgn** [comment]
- проект не выглядит как в примере

**Comment by ivklgn** [comment]
`email-container` и `bg_white` - нужно решить, в каком стиле именовать классы css. применительно к коду всех lw данного предмета

**Comment by ivklgn** [comment]
- форматирование index.html нарушено
- в css файле - открывающая фигурная скобка, перечисления `,`, `:` - отделяются пробелом спереди

**Comment by ivklgn** [comment]
устранить дублирование стилей у элементов в css

**Comment by ivklgn** [comment]
```css
.fontt {
  width:20%;
  text-align:right;
  padding: 0 2.5em;
  color: #000;
  padding-bottom: 20px"
}
```
fontt - так себе название. лучше заименовать по смыслу и уточнить написание по правилам англ. языка
